### ISSUE TITLE
Criar contador

### ISSUE THREAD

**Issue by RafaelFunchal** [rafaelfunchal/wordpress-security-checklist#4]
Inserir um contador para mostrar quantos itens restam em cada seção.

**Comment by fellyph** [comment]
Com js puro ou jquery/zepto @rafaelfunchal  ?

**Comment by RafaelFunchal** [comment]
Já estou inserindo jQuery no [footer](https://github.com/rafaelfunchal/wordpress-security-checklist/blob/master/_includes/footer.html#L55) , então pode ser com ele mesmo

**Comment by mariovalney** [comment]
Posso fazer?

**Comment by RafaelFunchal** [comment]
Sim, por favor
