### ISSUE TITLE
Google Authenticator

### ISSUE THREAD

**Issue by designfaustini** [rafaelfunchal/wordpress-security-checklist#40]
Boa iniciativa, mas não seria melhor sugerir a utilização do plugin "Google Authenticator" (compatível com a versão atual) do que o plugin "Google Authenticator for WordPress" (que teve sua última atualização há 2 anos)? 

Até pq fica contraditório quando chega no item Plugin, onde sugeri "Substitua plugins desatualizados por versões alternativas atualizadas". 

Apenas uma observação.

**Comment by RafaelFunchal** [comment]
Oi, @designfaustini !

Obrigado pela sugestão, mas como comentei lá no Facebook, fica mais fácil da alteração ser feita caso você mesmo a envie como Pull Request.

Você pode fazer isso forkando o projeto e fazendo as altrerações necessárias, depois disso é só enviar o código de volta para cá :-)

**Comment by RafaelFunchal** [comment]
@designfaustini , acabei de adicionar as instruções de como usar o projeto no readme:

https://github.com/RafaelFunchal/wordpress-security-checklist#como-instalar

Me avise caso tenha alguma dúvida.

**Comment by designfaustini** [comment]
Maravilha Rafael, amanhã vou seguir o readme e qualquer dúvida entro em contato. Obrigado.

**Comment by RafaelFunchal** [comment]
@designfaustini , se precisar de alguma ajuda para enviar o PR, é só falar.

**Comment by designfaustini** [comment]
Bom dia Rafael, desculpa cara, nem te dei um retorno... eu ainda não puide
mexer com isso, estou com alguns problemas de saúde na família e tem me
tomado muito tempo

Atenciosamente,

*Kindly confirm receipt of this.*

2017-03-07 10:07 GMT-03:00 Rafael Funchal <notifications@github.com>:

**Comment by RafaelFunchal** [comment]
Putz, que chato :(

Melhoras aí
