### ISSUE TITLE
WP Email Login

### ISSUE THREAD

**Issue by espellcaste** [rafaelfunchal/wordpress-security-checklist#5]
Na parte de login, você mostra o WP Email Login, esse plugin permite logar com e-mail ou com nome de usuário. Não apenas com e-mail.

**Comment by RafaelFunchal** [comment]
Não o testei recentemente, mas costumava funcionar.

Vou dar uma olhada nisso.

**Comment by espellcaste** [comment]
Eu estava testando ele para um site e notei isso. Achei estranho mas era exatamente o que precisava.

O que me chamou a atenção foi que ele diz que permite apenas logar por e-mail,
porém tem uma propriedade que altera o nome de "Username" para  "Username and Email".

**Comment by RafaelFunchal** [comment]
`Last Updated: 2014-12-10` :disappointed:

**Comment by espellcaste** [comment]
Só para reforçar, essa funcionalidade funciona seja com e-mail ou usuário. Testado e atualmente funcionando em alguns sites.

**Comment by espellcaste** [comment]
Talvez precise apenas atualizar a documentação para que possam ficar informado.

**Comment by marcos-alexandre82** [comment]
Tenho resolvido isso com este plugin:

https://wordpress.org/plugins/force-email-login/

Git: https://github.com/miya0001/force-email-login/blob/master/force-email-login.php

Ele permite apenas logar através do email.
Talvez seja pertinente alterar a documentação.

**Comment by RafaelFunchal** [comment]
@marcos-ucomm , me manda um PR alterando o plugin recomendado nos checklists?

**Comment by marcos-alexandre82** [comment]
@rafaelfunchal Mandei (veja se está tudo ok, rsrs)

**Comment by RafaelFunchal** [comment]
Esqueci de fechar essa issue quando o PR #33 foi enviado :(
